[build]
  publish = "public"

[[headers]]
  for = "/*.html"
  [headers.values]
    Netlify-CDN-Cache-Control = "public, max-age=0, stale-while-revalidate=86400"

[[headers]]
  for = "/posts.json"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

[functions]
  directory = "netlify/functions"

[functions."agent"]
  schedule = "0 7 * * *"
